SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100)) as FEE
FROM CAR_RENTAL_COMPANY_CAR as c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p
USING (CAR_TYPE)
WHERE c.CAR_TYPE IN ('세단', 'SUV')
    AND p.DURATION_TYPE = '30일 이상'
    AND 500000 <= c.DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100)
    AND c.DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100) < 2000000
    AND NOT c.CAR_ID IN (
        SELECT h.CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY as h
        WHERE h.END_DATE >= 20221101)
GROUP BY c.CAR_ID
ORDER BY FEE DESC, c.CAR_TYPE, c.CAR_ID DESC;