-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, SUM(PRICE) as TOTAL_SALES
FROM USED_GOODS_BOARD as ub
JOIN USED_GOODS_USER as u on ub.WRITER_ID=u.USER_ID
where STATUS='DONE'
Group by WRITER_ID
HAVING TOTAL_SALES>=700000
order by TOTAL_SALES;