-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(bs.SALES) as TOTAL_SALES
FROM BOOK_SALES as bs
JOIN BOOK as b ON b.BOOK_ID = bs.BOOK_ID
WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
GROUP BY CATEGORY
ORDER BY b.CATEGORY;
