-- 코드를 입력하세요
SELECT pr.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) as TOTAL_SALES
FROM FOOD_PRODUCT as pr
JOIN FOOD_ORDER as po
USING (PRODUCT_ID)
WHERE DATE_FORMAT(PRODUCE_DATE, "%Y-%m")='2022-05'
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID;
