-- 코드를 입력하세요
/*SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REST_REVIEW.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO
JOIN REST_REVIEW
ON REST_INFO.REST_ID=REST_REVIEW.REST_ID
WHERE REST_INFO.ADDRESS LIKE '서울%'
GROUP BY REST_INFO.REST_ID 
ORDER BY SCORE DESC, FAVORITES DESC;*/
SELECT i.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(r.REVIEW_SCORE),2) as SCORE
FROM REST_INFO as i
JOIN REST_REVIEW as r
USING(REST_ID)
WHERE ADDRESS LIKE '서울%'
GROUP BY i.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;